import type { GalleryCategory, GalleryPhoto } from "./types";

/**
 * The bundled local photo library — today this is the only `GalleryRepository`
 * implementation's data source. Every entry here has been visually verified as a genuine
 * photograph of Indian people/settings (no AI-generated faces, no foreign stock, no
 * illustrations). Nothing outside `repository.ts` should import this file directly.
 */
export const localGalleryPhotos: GalleryPhoto[] = [
  {
    id: "gallery-1",
    src: "/images/gallery/gallery-1.jpg",
    alt: "Student founders discussing their venture on the campus lawn",
    categories: ["students", "startup"],
    source: "local",
  },
  {
    id: "gallery-2",
    src: "/images/gallery/gallery-2.jpg",
    alt: "A founder briefing the team at the incubation centre",
    categories: ["startup", "government"],
    source: "local",
  },
  {
    id: "gallery-3",
    src: "/images/gallery/gallery-3.jpg",
    alt: "The team mapping out a product roadmap on a whiteboard",
    categories: ["startup", "networking"],
    source: "local",
  },
  {
    id: "gallery-4",
    src: "/images/gallery/gallery-4.jpg",
    alt: "A founder at the Tech4Bharat office",
    categories: ["startup", "awards"],
    source: "local",
  },
  {
    id: "gallery-5",
    src: "/images/gallery/gallery-5.jpg",
    alt: "The team planning sprints on a shared whiteboard",
    categories: ["startup", "networking"],
    source: "local",
  },
  {
    id: "gallery-6",
    src: "/images/gallery/gallery-6.jpg",
    alt: "Student innovators collaborating on a laptop during a mentorship session",
    categories: ["students", "mentorship", "women-entrepreneurship"],
    source: "local",
  },
  {
    id: "gallery-7",
    src: "/images/gallery/gallery-7.jpg",
    alt: "Founders working through a plan together over coffee",
    categories: ["mentorship", "hackathon"],
    source: "local",
  },
  {
    id: "gallery-8",
    src: "/images/gallery/gallery-8.jpg",
    alt: "Student developers at a college hackathon showcase",
    categories: ["hackathon", "students", "innovation"],
    source: "local",
  },
  {
    id: "gallery-9",
    src: "/images/gallery/gallery-9.jpg",
    alt: "Colleagues connecting during a team huddle",
    categories: ["networking", "startup"],
    source: "local",
  },
  {
    id: "gallery-10",
    src: "/images/gallery/gallery-10.jpg",
    alt: "Team members networking at the Tech4Bharat office",
    categories: ["networking", "government"],
    source: "local",
  },
  {
    id: "gallery-11",
    src: "/images/gallery/gallery-11.jpg",
    alt: "Founders celebrating a new hire at the incubation centre",
    categories: ["awards", "startup"],
    source: "local",
  },
  {
    id: "gallery-12",
    src: "/images/gallery/gallery-12.jpg",
    alt: "Mentors and founders in conversation",
    categories: ["networking", "mentorship"],
    source: "local",
  },
  {
    id: "gallery-13",
    src: "/images/gallery/gallery-13.jpg",
    alt: "A founder reflecting between working sessions",
    categories: ["research", "startup"],
    source: "local",
  },
  {
    id: "gallery-14",
    src: "/images/gallery/gallery-14.jpg",
    alt: "The team celebrating together at the office",
    categories: ["awards", "networking"],
    source: "local",
  },
  {
    id: "gallery-15",
    src: "/images/gallery/gallery-15.jpg",
    alt: "A founder and mentor collaborating over a laptop at home",
    categories: ["mentorship", "networking"],
    source: "local",
  },
  {
    id: "hackathons-2",
    src: "/images/gallery/hackathons-2.jpg",
    alt: "Founders pairing on code during a hackathon sprint",
    categories: ["hackathon", "innovation", "research"],
    source: "local",
  },
  {
    id: "hackathons-3",
    src: "/images/gallery/hackathons-3.jpg",
    alt: "Student developers crowded around a laptop at a college hackathon",
    categories: ["hackathon", "students", "innovation"],
    source: "local",
  },
  {
    id: "agriculture-1",
    src: "/images/gallery/agriculture-1.jpg",
    alt: "An AgriTech founder surveying a wheat field near his family farm",
    categories: ["agriculture", "innovation"],
    source: "local",
  },
  {
    id: "agriculture-2",
    src: "/images/gallery/agriculture-2.jpg",
    alt: "A woman farmer at work in the field",
    categories: ["agriculture", "women-entrepreneurship"],
    source: "local",
  },
  {
    id: "agriculture-3",
    src: "/images/gallery/agriculture-3.jpg",
    alt: "Women farmers operating equipment in a cotton field",
    categories: ["agriculture", "women-entrepreneurship"],
    source: "local",
  },
  {
    id: "students-1",
    src: "/images/gallery/students-1.jpg",
    alt: "A student researching in the campus library",
    categories: ["students", "research"],
    source: "local",
  },
  {
    id: "students-3",
    src: "/images/gallery/students-3.jpg",
    alt: "Students reviewing a project together outdoors on campus",
    categories: ["students", "networking"],
    source: "local",
  },
  {
    id: "domains-agritech",
    src: "/images/domains/agritech.jpg",
    alt: "Women farmers operating a tractor supported by an AgriTech innovation",
    categories: ["agriculture", "women-entrepreneurship"],
    source: "local",
  },
  {
    id: "domains-healthtech",
    src: "/images/domains/healthtech.jpg",
    alt: "A HealthTech founder and clinician at a partner hospital",
    categories: ["women-entrepreneurship", "research"],
    source: "local",
  },
  {
    id: "programs-incubation",
    src: "/images/programs/incubation.jpg",
    alt: "Founders and mentors in a strategy session at the incubation centre",
    categories: ["startup", "government"],
    source: "local",
  },
  {
    id: "programs-mentoring",
    src: "/images/programs/mentoring.jpg",
    alt: "Student mentees collaborating on a laptop during a mentorship session",
    categories: ["mentorship", "women-entrepreneurship", "students"],
    source: "local",
  },
  {
    id: "about-team",
    src: "/images/about/team.png",
    alt: "The Tech4Bharat team collaborating at the innovation centre",
    categories: ["startup", "networking"],
    source: "local",
  },
];

export const localGalleryCategories: GalleryCategory[] = [
  { slug: "startup", label: "Startup" },
  { slug: "hackathon", label: "Hackathon" },
  { slug: "students", label: "Students" },
  { slug: "women-entrepreneurship", label: "Women Entrepreneurship" },
  { slug: "agriculture", label: "Agriculture" },
  { slug: "mentorship", label: "Mentorship" },
  { slug: "networking", label: "Networking" },
  { slug: "innovation", label: "Innovation" },
  { slug: "government", label: "Government" },
  { slug: "research", label: "Research" },
  { slug: "awards", label: "Awards" },
];
